// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using roulette_casino_api.Models.Data;

#nullable disable

namespace roulette_casino_api.Migrations
{
    [DbContext(typeof(RouletteCasinoDbContext))]
    [Migration("20240610105854_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("roulette_casino_api.Models.Entities.UserAccount", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
